### ISSUE TITLE
MsgSrvDoc doesn't match the selected ROS version

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/roswiki#241] opened 2018-01-31 19:35 UTC
I noticed unwanted side effects in two use cases:

1) Content not displayed
- I have a package released in ROS Kinetic and not Lunar
- the roswiki default version switches to Lunar
- Result: the ROS interfaces of my package are not displayed anymore and I get this error message instead: `Newly proposed, mistyped, or obsolete package. Could not find package "<PACKAGE_NAME>" in rosdoc: /home/rosbot/docs/api/naoqi_bridge_msgs/manifest.yaml`
- example: http://wiki.ros.org/naoqi_bridge_msgs

2) Wrong content displayed
- I release a new version of my package for ROS Lunar with new ROS interfaces in it
- the roswiki default version switches to Lunar
- Result: if I select any ROS distribution prior to Lunar, the Wiki page displays the interfaces of Lunar and not of the selected distro
- example: sensor_msgs/BatteryState in `groovy` doesnt exist but is displayed: http://wiki.ros.org/sensor_msgs

**Comment by dirk-thomas** [comment] 2018-01-31 19:36
Duplicate of #137?

**Comment by mikaelarguedas** [comment] 2018-01-31 19:47
Indeed, thanks for pointing it out.

I'll let the maintainers decide if they prefer to close this or to this summary as an open issue labeled as duplicate

**Closed** 2018-01-31 19:56 UTC
Labels: duplicate
