### ISSUE TITLE
keyserver is "down" a lot

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/roswiki#140] opened 2016-01-13 07:21 UTC
I've seen a fair number of questions on ROS answers recently about what to do when the keyserver is down. The most recent is http://answers.ros.org/question/223996/how-to-install-ros-indigo-in-ubuntu-14043-lts-desktop-64-bit/

In addition, it looks like HKP is currently down or not turned on on more than half of the keyservers in the sks-keyservers pool: https://sks-keyservers.net/status/ .

I'm not familiar enough with the keyserver setup to understand why ROS switched away from self-hosted keys, or what our alternatives are if we want to switch to a more robust key retrieval tool or a more robust protocol, but it seems obvious that we should do something about this.

For every user who asks a question, there are doubtless many more who turn away because they can't get through the installation.

**Comment by gavanderhoorn** [comment] 2016-01-13 08:19
I've been handling quite some questions about this as well. A quick [google](https://www.google.nl/search?q=%22pool.sks-keyservers.net:+Host+not+found%22) shows we're not alone.

Note that in some cases similar issues can be caused by overzealous firewalls interfering with `hkp`. In those cases running `sudo apt-key adv --keyserver p80.pool.sks-keyservers.net:80 --recv-keys ...` can help.

This obviously won't help with unresolvable hostnames.

**Comment by wjwwood** [comment] 2016-01-13 08:46
Perhaps @jspricke can comment, he originally suggested we switch to a key server. I believe the idea was that it was more stable than GitHub which may or may not be true, but I'm open to do what ever if someone has a better suggestion. See:

http://wiki.ros.org/action/diff/jade/Installation/Sources?action=diff&rev1=2&rev2=3

**Comment by tfoote** [comment] 2016-01-13 09:02
Using the keyservers is considered the most secure. There's a good overview of best practices on the docker official images guide: https://github.com/docker-library/official-images

Note I see them recommending a slightly different url with "high availability" which we should probably switch to use the `ha.pool.sks-keyservers.net`

**Comment by trainman419** [comment] 2016-01-13 09:05
I like the thought of switching to the "high-availability" pool.

Can we track the status of the keyserver on status.ros.org , so that we can collect better data on how well it's (probably) working for new users?

**Comment by gavanderhoorn** [comment] 2016-01-13 09:24
@tfoote wrote:
> Note I see them recommending a slightly different url with "high availability" which we should probably switch to use the `ha.pool.sks-keyservers.net`

According to [this](https://github.com/docker/docker/issues/13555#issuecomment-126315460) comment by @krifisk, the `ha` pool is nothing special 'at the moment' (2015-07-30):

> 1) ha.pool is currently not doing anything special, it is kept around for backwards compatibility and will be used down the line for servers that are clustered, but for a while all keyservers in the main pool require a reverse proxy (which was the original use for ha pool)

Not sure we want to recommend that to our users then?

**Comment by krifisk** [comment] 2016-01-13 13:45
> On 13 Jan 2016, at 10:24, G.A. vd. Hoorn <notifications@github.com> wrote:
> 
> @tfoote wrote:
> 
> Note I see them recommending a slightly different url with "high availability" which we should probably switch to use the ha.pool.sks-keyservers.net
> 
> According to this comment by @krifisk, the ha pool is nothing special 'at the moment' (2015-07-30):
> 
> 1) ha.pool is currently not doing anything special, it is kept around for backwards compatibility and will be used down the line for servers that are clustered, but for a while all keyservers in the main pool require a reverse proxy (which was the original use for ha pool)
> 
> Not sure we want to recommend that to our users then?
> 
> 
> 

the HA pool is now restricted to servers with load balanced / clustered setups as indicated above, so it currently differ from the normal pool again.

On a side note, aside from firewall issues for hkp / port 11371, another common problem are users with invalid IPv6 setups resulting in timeout. This can be countered by using ipv4 specific subpool at ipv4.pool.sks-keyservers.net 

K_F

**Comment by trainman419** [comment] 2016-02-24 07:26
This continues to be a problem for new users: http://answers.ros.org/question/227228/cant-set-up-keys-server-times-out/

**Comment by trainman419** [comment] 2016-02-24 07:28
I have confirmed that the ha pool appears to have our key (or at least, the one server that I hit has it). I am going to switch the wiki pages to reference the high-availability pool.

**Comment by tfoote** [comment] 2016-02-24 07:39
Sounds good.

**Comment by trainman419** [comment] 2016-02-24 07:41
I dug a little more, and was able to retrieve our key from all seven servers that show up with an IPv4 address in the round-robin DNS for the ha pool:

```
$ host ha.pool.sks-keyservers.net
ha.pool.sks-keyservers.net has address 79.143.214.213
ha.pool.sks-keyservers.net has address 104.131.67.179
ha.pool.sks-keyservers.net has address 104.236.209.43
ha.pool.sks-keyservers.net has address 178.32.66.144
ha.pool.sks-keyservers.net has address 178.62.8.85
ha.pool.sks-keyservers.net has address 37.191.220.247
ha.pool.sks-keyservers.net has address 67.205.56.66
```

I'm going to update the tutorials to use the ha pool.

**Comment by trainman419** [comment] 2016-02-24 07:54
I have updated the keyserver link on the following pages to use the HA pool:

- http://wiki.ros.org/jade/Installation/Ubuntu
- http://wiki.ros.org/jade/Installation/UbuntuARM
- http://wiki.ros.org/jade/Installation/Sources
- http://wiki.ros.org/indigo/Installation/Ubuntu
- http://wiki.ros.org/indigo/Installation/UbuntuARM
- http://wiki.ros.org/indigo/Installation/Sources
- http://wiki.ros.org/Debian/Installation/Source

**Comment by wjwwood** [comment] 2016-02-24 08:23
Thanks @trainman419! Can this be closed now?

**Comment by trainman419** [comment] 2016-02-24 08:29
I don't think we can mark this as resolved until we see a lack of problems reported on answers.ros.org for some period of time, or until someone implements monitoring on the keyserver uptime.

We've only seen a few issues over the past 1.5 months, so I propose that we leave this open for another 2 months, and close it if we haven't seen this resurface within that time frame.

**Comment by ramanpreet9** [comment] 2016-07-11 04:31
the tutorials seem to list the old keyserver which doesnt work for me. 
Is there any working server to set up the keys currently?

**Comment by tfoote** [comment] 2016-07-11 05:31
The key server is working for me at the moment. 
```
$ docker run -ti --rm ubuntu:trusty
root@59dd273ba8fe:/# sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.ZjQsHPSKn4 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116
gpg: requesting key B01FA116 from hkp server ha.pool.sks-keyservers.net
gpg: key B01FA116: public key "ROS Builder <rosbuild@ros.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by BrettHemes** [comment] 2017-04-14 15:18
FYI, I just had this problem as of this morning...
```
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
Executing: /tmp/tmp.hLvqknRuQH/gpg.1.sh --keyserver
hkp://ha.pool.sks-keyservers.net:80
--recv-key
421C365BD9FF1F717815A3895523BAEEB01FA116
gpg: requesting key B01FA116 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
```
I found a note for `hkp://keyserver.ubuntu.com:80` in another similar issue and that seems to have worked

**Comment by dhood** [comment] 2017-04-14 22:21
[Docker added](https://github.com/docker/docker/commit/adac575dd33c48b19539c0f0660c5c3f344c7b75) a couple of failover keyservers for their install scripts including `hkp://keyserver.ubuntu.com:80` as mentioned by @BrettHemes and `hkp://pgp.mit.edu:80`. I refactored the indigo-and-up pages to use http://wiki.ros.org/Installation/Ubuntu/Sources which now lists two backups.

More recently Docker has switched to just [listing the key themselves](https://github.com/docker/docker/commit/91b42cf8428ec20c3d6775019ed04d89330c1dcd) but hopefully this is sufficient for our users.

**Comment by dhood** [comment] 2017-07-25 17:53
I'll close this out under the understanding that listing two backup keyservers is a sufficient fix. I haven't seen questions about it on ros answers lately and users installing from scripts have had success looping over the keyservers as in the aforementioned docker install script e.g. https://github.com/mcgill-robotics/compsys/pull/40. Please let me know if any of these points are off the mark and we can reopen

**Closed by dhood** 2017-07-25 17:53 UTC
