### ISSUE TITLE
Whitelisted users unable to edit

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/roswiki#210] opened 2017-04-20 23:35 UTC
I added two users this afternoon http://wiki.ros.org/action/diff/UserGroup?action=diff&rev1=528&rev2=529

And I got an error message that I couldn't edit the page anymore when the editor reopened.

I cannot edit a page anymore. And other users are reporting they cannot either [here](https://github.com/ros-infrastructure/roswiki/issues/139#issuecomment-295962098)

I'm not sure what happened it appears the whitelist mechanism is broken.

**Comment by dhood** [comment] 2017-04-20 23:40
I am able to edit [this page, for example](http://wiki.ros.org/action/fullsearch/testing_page)

Is there a particular error message that you get?

**Comment by tfoote** [comment] 2017-04-20 23:40
I reverted that change on the server and editing is working for me again. 

Here's the diff that used to exist before I edited it. 

![diff_529](https://cloud.githubusercontent.com/assets/447804/25256747/fc89c518-25e7-11e7-8994-6ada96f91b88.png)

**Comment by wjwwood** [comment] 2017-04-21 01:06
@tfoote I recently (like a week ago) added you to the ACL of this page so only you and I could edit it (prevent users from trying to extend it):

http://wiki.ros.org/Robots/Backup

<img width="802" alt="screen shot 2017-04-20 at 6 05 35 pm" src="https://cloud.githubusercontent.com/assets/100427/25258394/fe2ed91a-25f3-11e7-99d8-d77c25e8d294.png">

I don't think that should do anything, but I thought I'd bring it up since it's vaguely wik and permissions related. I could have screwed something up.

**Comment by tfoote** [comment] 2017-04-22 18:09
@wjwwood That acl makes sense. But I was having trouble editing /TullyFoote so I don't think it's related. 

@dhood The error I was getting is the little pop up that you should go ask for permission and the page is flagged as immutable. 

Now that I've reverted the linked change editing is working. When that change was applied I was unable to edit any page on the wiki. To debug I'd suggest reapplying the changes above. I kept a copy of the revision in the wiki database with a `.bak`extension.

**Comment by dhood** [comment] 2017-05-01 17:34
restored the original revision that added the 2 new users on the server (and reloaded httpd) and editing still seems to be working fine. no insight into what the cause was. last time the issue was reported ~20 minutes after the revision, so I'll check it's still working fine later in the day and otherwise I'd say we're back to business as usual.

**Comment by dhood** [comment] 2017-05-01 18:43
editing still seems good after adding more users. going to close this because it appears to have fixed itself.

**Closed by dhood** 2017-05-01 18:43 UTC
